version: '2'

services:
  retroarch:
    image: inglebard/retroarch-web
    container_name: retroarch 
  bigtop:
    build:
      context: ./src
    container_name: bigtop
    networks:
      - traefik_wan
    labels:
      - "traefik.port=8080"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:bigtop.test.abcm.ch"
      - "traefik.docker.network=traefik_wan"

networks:
  traefik_wan:
    external: true


# vim: ft=yaml tw=80 et ts=2 st=2 sts=2
